export enum GameScreen {
  NONE = 'NONE',
  CHARACTER = 'CHARACTER',
  GAME = 'GAME',
  GAME_OVER = 'GAME_OVER',
  HELP = 'HELP',
  INVENTORY = 'INVENTORY',
  MAP = 'MAP',
  TITLE = 'TITLE',
  VICTORY = 'VICTORY'
}
