packages:
  - 'assets'
  - 'audio'
  - 'features'
  - 'geometry'
  - 'graphics'
  - 'main'
  - 'models'
  - 'utils'

catalog:
  '@types/node': '^22.7.4'
  'glob': '^11.0.0'
  'globals': '^15.10.0'
  'prettier': '^3.3.3'
  'rimraf': '^6.0.1'

catalogs:
  pathfinding:
    'pathfinding': '^0.4.18'
    '@types/pathfinding': '^0.0.9'
  tsx:
    'tsx': '^4.20.6'
  typescript:
    'typescript': '~5.5.4'
  vite:
    'vite': '^7.2.2'
  vitest:
    'vitest': '^4.0.10'
    '@vitest/coverage-v8': '^4.0.10'
  zod:
    'zod': '^4.0.5'
