import { MusicController, SoundPlayer } from '@duzh/audio';
import { AssetBundle } from '@main/assets/AssetBundle';
import { InventoryController } from '@main/controllers/InventoryController';
import { ShrineController } from '@main/controllers/ShrineController';
import { Engine } from '@main/core/Engine';
import { GameConfig } from '@main/core/GameConfig';
import { GameState } from '@main/core/GameState';
import Ticker from '@main/core/Ticker';
import { ItemController } from '@main/items/ItemController';
import { ItemFactory } from '@main/items/ItemFactory';
import { MapController } from '@main/maps/MapController';
import ObjectFactory from '@main/objects/ObjectFactory';
import ProjectileFactory from '@main/objects/ProjectileFactory';
import UnitFactory from '@main/units/UnitFactory';

export type Game = Readonly<{
  config: GameConfig;
  engine: Engine;
  state: GameState;
  assetBundle: AssetBundle;
  itemFactory: ItemFactory;
  unitFactory: UnitFactory;
  objectFactory: ObjectFactory;
  musicController: MusicController;
  projectileFactory: ProjectileFactory;
  soundPlayer: SoundPlayer;
  mapController: MapController;
  inventoryController: InventoryController;
  shrineController: ShrineController;
  itemController: ItemController;
  ticker: Ticker;
}>;
