/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DynamicSpriteModel {
  animations: {
    [k: string]: DynamicSprite_Animation;
  };
  name: string;
  offsets: DynamicSprite_Offsets;
  pattern?: string;
  patterns?: string[];
  transparentColor?: string;
}
export interface DynamicSprite_Animation {
  frames: {
    activity: string;
    number: string;
    [k: string]: unknown;
  }[];
  pattern?: string;
  [k: string]: unknown;
}
export interface DynamicSprite_Offsets {
  dx: number;
  dy: number;
  [k: string]: unknown;
}
