/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeneratedMapModel {
  layout: string;
  tileSet: string;
  levelNumber: number;
  width: number;
  height: number;
  enemies: {
    [k: string]: number;
  };
  equipment: {
    [k: string]: number;
  };
  items: {
    [k: string]: number;
  };
}
