/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StaticSpriteModel {
  name: string;
  filename: string;
  offsets: {
    dx: number;
    dy: number;
    [k: string]: unknown;
  };
  transparentColor: string;
}
