/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UnitModel {
  /**
   * TODO: This includes ATTACK at position 0, followed by special abilities.
   * It doesn't include SHOOT_ARROW.
   */
  abilities: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[0-9]+$".
     */
    [k: string]: string[];
  };
  aiParameters?: {
    /**
     * ratio of (current life / max life)
     */
    fleeThreshold: number;
    /**
     * between 0 and 1
     */
    speed: number;
    /**
     * whole number of tiles
     */
    visionRange: number;
    [k: string]: unknown;
  };
  equipment?: string[];
  damagePerLevel?: number | null;
  experienceToNextLevel?: number[];
  lifePerLevel?: number | null;
  manaPerLevel?: number | null;
  name: string;
  paletteSwaps: PaletteSwapsModel;
  sprite: string;
  startingDamage: number;
  startingLife: number;
  startingMana: number | null;
  summonedUnitClass?: string;
  type: string;
}
export interface PaletteSwapsModel {
  /**
   * This interface was referenced by `PaletteSwapsModel`'s JSON-Schema definition
   * via the `patternProperty` "^[A-Z_]+$".
   */
  [k: string]: string;
}
