export enum AbilityName {
  ATTACK = 'ATTACK',
  HEAVY_ATTACK = 'HEAVY_ATTACK',
  KNOCKBACK_ATTACK = 'KNOCKBACK_ATTACK',
  STUN_ATTACK = 'STUN_ATTACK',
  SHOOT_ARROW = 'SHOOT_ARROW',
  DASH = 'DASH',
  TELEPORT = 'TELEPORT',
  SUMMON = 'SUMMON',
  BOLT = 'BOLT',
  STRAFE = 'STRAFE',
  PIERCE = 'PIERCE'
}