export enum AbilityName {
  ATTACK = 'ATTACK',
  BOLT = 'BOLT',
  DASH = 'DASH',
  HEAVY_ATTACK = 'HEAVY_ATTACK',
  KNOCKBACK_ATTACK = 'KNOCKBACK_ATTACK',
  MINOR_STUN_ATTACK = 'MINOR_STUN_ATTACK',
  PIERCE = 'PIERCE',
  SHOOT_ARROW = 'SHOOT_ARROW',
  SUMMON = 'SUMMON',
  STRAFE = 'STRAFE',
  STUN_ATTACK = 'STUN_ATTACK',
  TELEPORT = 'TELEPORT'
}