export enum TileType {
  FLOOR = 'FLOOR',
  FLOOR_HALL = 'FLOOR_HALL',
  WALL_TOP = 'WALL_TOP',
  WALL_HALL = 'WALL_HALL',
  WALL = 'WALL',
  NONE = 'NONE',
  STAIRS_DOWN = 'STAIRS_DOWN',
  STAIRS_UP = 'STAIRS_UP'
}
